// 表单设计器逐类型 props 模板（自动生成，源自 word-form-autobookmark/designer-template.js）
// 仅用于 buildDesignerTree 深拷贝，保证生成节点与你设计器期望的 props 完全一致。
export interface DesignerProps { [key: string]: unknown; }
export const DESIGNER_TEMPLATE: Record<string, DesignerProps> = {
  "form": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [
      {
        "event": "created",
        "codeItem": {
          "code": "module.exports = async function (params, ctx, block) {\n  debugger;\n  const gcmc = ctx.getValue(\"input_xjtc8vx7rddj4j8c9c\"); // 项目名称\n  const jlmc = ctx.getValue(\"input_mizfi5xjbxfxasd6dd\"); // 监理名称\n\n  if (!gcmc && !jlmc) {\n    try {\n      // 项目名称\n      const resGcmc = await ctx.http.request(\n        \"POST\",\n        \"/dynamic/function/api/table\",\n      )({\n        tbName: \"sys_web_config\",\n        fields: [\"attribute_value\"],\n        queryMap: { attribute_name: \"gcmc\" },\n      });\n\n      if (resGcmc && resGcmc.length > 0) {\n        ctx.setValue(\"input_xjtc8vx7rddj4j8c9c\", resGcmc[0].attribute_value);\n      }\n\n      // 监理名称\n      const resJlmc = await ctx.http.request(\n        \"POST\",\n        \"/dynamic/function/api/table\",\n      )({\n        tbName: \"sys_web_config\",\n        fields: [\"attribute_value\"],\n        queryMap: { attribute_name: \"jlmc\" },\n      });\n\n      if (resJlmc && resJlmc.length > 0) {\n        ctx.setValue(\"input_mizfi5xjbxfxasd6dd\", resJlmc[0].attribute_value);\n      }\n    } catch (error) {\n      console.error(\"获取配置信息失败:\", error);\n    }\n  }\n};\n",
          "utils": []
        }
      }
    ],
    "labelPosition": "left",
    "width": "100%",
    "size": "middle",
    "useLabelWidth": true,
    "labelWidth": "110px",
    "labelSpan": 3,
    "colon": true,
    "useDefaultGrid": true,
    "defaultGridSize": 4,
    "disabled": false,
    "datasourcePool": [],
    "stylesheets": [
      {
        "title": "main",
        "desc": "主样式",
        "code": ".css-1ku1uke > label {\n  white-space: normal;\n}\n.ant-form-item-required:before {\n  margin-inline-end: 0px !important;\n}\n.input-number-plus {\n  text-align: right;\n}\n.adm-form .row_kx00irvnjhc4lk795f {\n  margin-top: 0px !important;\n}\n.adm-form .checkbox_yle4it5b6lz2nbcuz1-form-item .adm-space-horizontal {\n  justify-content: flex-start !important;\n}\n.adm-form .input_ehx4jqd09ojg4pmpo2-form-item .adm-list-item-content-prefix {\n  width: max-content !important;\n}\n"
      }
    ],
    "utilsJs": [],
    "relations": []
  },
  "collapse": {
    "visible": false,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "mobileHidden": true,
    "defaultActiveKey": [
      "collapse-pane_dsaq1hvm8k3wkcgj1v"
    ],
    "accordion": false,
    "bordered": true,
    "ghost": false,
    "expandIconPosition": "start"
  },
  "collapse-pane": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "label": "基础字段",
    "disabled": false
  },
  "row": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "flex": true,
    "gutter": 12,
    "align": "top",
    "justify": "start",
    "disabled": false
  },
  "col": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "flex": "1",
    "responsive": false,
    "span": 24,
    "offset": 0,
    "push": 0,
    "pull": 0,
    "xs": 24,
    "sm": 24,
    "md": 24,
    "lg": 24,
    "xl": 24
  },
  "input": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "id",
    "fieldLength": 32,
    "dataBind": "input_0wfgafmrf95lb0mz46",
    "label": "主键ID",
    "labelHidden": false,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "placeholder": "请输入",
    "contentAlign": "left",
    "defaultValue": null,
    "isAutoComplete": false,
    "options": [],
    "dataSourceFn": "",
    "isPassword": false,
    "alertInput": false,
    "isSelectModal": false,
    "selectDataSource": {},
    "selectField": "",
    "modalbindFiled": "",
    "currentSelectItems": [],
    "selectMultiple": false,
    "selectDisabled": false,
    "selectLink": false,
    "selectModalHeight": null,
    "conditionsStr": "",
    "conditions": [],
    "advanceConditions": [],
    "advanceConditionsStr": "",
    "linkSetting": "none",
    "fixedLink": "",
    "customModal": false,
    "textWrap": true,
    "modalCode": "import React from \"react\";\nimport { Input } from \"antd\";\nimport dayjs from \"dayjs\";\nimport _ from \"lodash\";\n\nexport default function Component({\n  value,\n  onChange,\n  ctx,\n  useWatch,\n}) {\n  return (\n    <>\n      <Input onChange={(e) => onChange(e.target.value)} />\n    </>\n  );\n}\n",
    "completedModalCode": "\"use strict\";\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = Component;\nvar _react = _interopRequireDefault(require(\"react\"));\nvar _antd = require(\"antd\");\nvar _dayjs = _interopRequireDefault(require(\"dayjs\"));\nvar _lodash = _interopRequireDefault(require(\"lodash\"));\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\nfunction Component(_ref) {\n  var value = _ref.value,\n    _onChange = _ref.onChange,\n    ctx = _ref.ctx,\n    useWatch = _ref.useWatch;\n  return /*#__PURE__*/_react.default.createElement(_react.default.Fragment, null, /*#__PURE__*/_react.default.createElement(_antd.Input, {\n    onChange: function onChange(e) {\n      return _onChange(e.target.value);\n    }\n  }));\n}",
    "mobileModalCode": "import React from \"react\";\nimport { Input } from \"antd-mobile\";\nimport dayjs from \"dayjs\";\nimport _ from \"lodash\";\n\nexport default function Component({ value, onChange, ctx, useWatch }) {\n  return (\n    <>\n      <Input onChange={onChange} />\n    </>\n  );\n}\n",
    "mobileCompletedModalCode": "\"use strict\";\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = Component;\nvar _react = _interopRequireDefault(require(\"react\"));\nvar _antdMobile = require(\"antd-mobile\");\nvar _dayjs = _interopRequireDefault(require(\"dayjs\"));\nvar _lodash = _interopRequireDefault(require(\"lodash\"));\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\nfunction Component(_ref) {\n  var value = _ref.value,\n    onChange = _ref.onChange,\n    ctx = _ref.ctx,\n    useWatch = _ref.useWatch;\n  return /*#__PURE__*/_react.default.createElement(_react.default.Fragment, null, /*#__PURE__*/_react.default.createElement(_antdMobile.Input, {\n    onChange: onChange\n  }));\n}"
  },
  "select": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": true,
    "virtualBindingTable": "sys_dictionary_value",
    "virtualBindingField": "label",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "flow_bizstate",
    "fieldLength": 64,
    "dataBind": "select_75kfnh4s5b3fjok91m",
    "label": "流程状态",
    "labelHidden": false,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "showLabel": false,
    "dataSourceType": "dictionary",
    "options": [
      {
        "code": "unstart",
        "value": "FlowTemplateStates-flowstate-unstart",
        "aySerial": 1,
        "soleNum": "FlowTemplateStates-flowstate-unstart",
        "ovalue": "未启动",
        "label": "未启动"
      },
      {
        "code": "going",
        "value": "FlowTemplateStates-flowstate-going",
        "aySerial": 2,
        "soleNum": "FlowTemplateStates-flowstate-going",
        "ovalue": "流程中",
        "label": "流程中"
      },
      {
        "code": "finish",
        "value": "FlowTemplateStates-flowstate-finish",
        "aySerial": 3,
        "soleNum": "FlowTemplateStates-flowstate-finish",
        "ovalue": "已完成",
        "label": "已完成"
      },
      {
        "code": "reject",
        "value": "FlowTemplateStates-flowstate-reject",
        "aySerial": 4,
        "soleNum": "FlowTemplateStates-flowstate-reject",
        "ovalue": "驳回",
        "label": "驳回"
      },
      {
        "code": "end",
        "value": "FlowTemplateStates-flowstate-end",
        "aySerial": 5,
        "soleNum": "FlowTemplateStates-flowstate-end",
        "ovalue": "终止",
        "label": "终止"
      }
    ],
    "dictionaryType": "FlowTemplateStates-flowstate",
    "dataSourceFn": "",
    "placeholder": "请选择",
    "defaultValue": "FlowTemplateStates-flowstate-unstart",
    "multiple": false,
    "filterable": false
  },
  "text": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "bdh",
    "fieldLength": null,
    "dataBind": "text_7gvm6oopjaf8oe9nt0",
    "label": "表单号",
    "labelHidden": true,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "defaultValue": "-B37-",
    "fontSize": 16,
    "color": "#000",
    "textAlign": "left",
    "lineHeight": "16px",
    "bold": false,
    "em": false,
    "underline": false,
    "del": false,
    "nowrap": false
  },
  "table": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "borderColor": "#000",
    "borderWidth": 1,
    "disabled": false
  },
  "list-row": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": []
  },
  "table-cell": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "colSpan": 1,
    "rowSpan": 1
  },
  "office": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "jbr",
    "fieldLength": null,
    "dataBind": "office_qyebk5yr7l9cei1ume",
    "label": "项目技术负责人",
    "labelHidden": false,
    "labelCustomWidth": true,
    "useLabelWidth": true,
    "labelWidth": "120px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": true,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "placeholder": "请选择人员",
    "defaultValue": null,
    "multiple": true,
    "filterable": false,
    "current": false,
    "manualInput": false,
    "valueRange": "currentCap",
    "dataNameField": "jbr_name",
    "currentOrg": null,
    "customFilter": false,
    "customFilterFn": "module.exports=function(users, orgs, pos) {\n\n}",
    "customFilterAdvanced": false,
    "customFilterFnAdvanced": "module.exports=function(params, ctx, block) {\n\n}",
    "userGroupList": [],
    "expandRange": "none",
    "expandRangeName": ""
  },
  "date": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "jbrrq",
    "fieldLength": null,
    "dataBind": "date_yf8n2y9t0mffuki22x",
    "label": "日期",
    "labelHidden": false,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": true,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "defaultValue": "",
    "placeholder": "请选择",
    "timestamp": false,
    "format": "YYYY-MM-DD",
    "range": [
      null,
      null
    ],
    "type": "date",
    "inputReadOnly": false,
    "current": false
  },
  "textarea": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsb",
    "dataField": "zyjlyj",
    "fieldLength": null,
    "dataBind": "textarea_0ikh1mcdj02ckfsvt0",
    "label": "专业监理意见",
    "labelHidden": false,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": true,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "placeholder": "",
    "defaultValue": "",
    "autoSize": true,
    "minRows": 1,
    "maxRows": 6,
    "contentAlign": "left"
  },
  "subtable": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsbzb",
    "dataField": "",
    "fieldLength": null,
    "dataBind": "subtable_fl1vdy5p5qysqk6d35",
    "label": "明细子表",
    "labelHidden": true,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "visibleIndexColumn": true,
    "visibleIndexColumnField": "ay_serial",
    "formId": "",
    "functionId": "",
    "bindCode": "",
    "viewBtnText": "查看",
    "usePagination": true,
    "canRemove": true,
    "canAdd": true,
    "canWatch": false,
    "showOptions": true,
    "canSelect": false,
    "delAuth": "module.exports=function(ctx,records,index) {\n return true;\n}",
    "selectType": "checkbox",
    "summary": false,
    "summaryColumns": [],
    "dragSort": true,
    "subTabAddMethod": "0",
    "isDetailEdit": false,
    "briefDisplay": false,
    "briefCount": 5,
    "briefColumns": [],
    "selectedRows": [],
    "tableLabel": "",
    "height": "200px",
    "subtableFixedColumn": [],
    "showType": "list",
    "mobileContentCustomCode": "import React from \"react\";\nimport { Input } from \"antd-mobile\";\nimport dayjs from \"dayjs\";\nimport _ from \"lodash\";\nexport default function Component({ record, ctx, subtable, rowInfo }) {\n  return (\n    <div>\n      {Object?.entries(record)?.map(([key, value], index) => {\n        return (\n          <div\n            key={key}\n            style={{\n              display: \"flex\",\n            }}\n          >\n            <div\n              style={{\n                color: \"#000\",\n                fontSize: \"16px\",\n                fontWight: 600,\n              }}\n            >\n              {rowInfo?.[key]?.label}:\n            </div>\n\n            <div\n              style={{\n                color: \"#000\",\n                fontSize: \"16px\",\n              }}\n            >\n              {value}\n            </div>\n          </div>\n        );\n      })}\n    </div>\n  );\n}\n",
    "mobileCompletedContentCustomCode": "\"use strict\";\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = Component;\nvar _react = _interopRequireDefault(require(\"react\"));\nvar _antdMobile = require(\"antd-mobile\");\nvar _dayjs = _interopRequireDefault(require(\"dayjs\"));\nvar _lodash = _interopRequireDefault(require(\"lodash\"));\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\nfunction _slicedToArray(arr, i) { return _arrayWithHoles(arr) || _iterableToArrayLimit(arr, i) || _unsupportedIterableToArray(arr, i) || _nonIterableRest(); }\nfunction _nonIterableRest() { throw new TypeError(\"Invalid attempt to destructure non-iterable instance.\\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.\"); }\nfunction _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === \"string\") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === \"Object\" && o.constructor) n = o.constructor.name; if (n === \"Map\" || n === \"Set\") return Array.from(o); if (n === \"Arguments\" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }\nfunction _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i]; return arr2; }\nfunction _iterableToArrayLimit(arr, i) { var _i = null == arr ? null : \"undefined\" != typeof Symbol && arr[Symbol.iterator] || arr[\"@@iterator\"]; if (null != _i) { var _s, _e, _x, _r, _arr = [], _n = !0, _d = !1; try { if (_x = (_i = _i.call(arr)).next, 0 === i) { if (Object(_i) !== _i) return; _n = !1; } else for (; !(_n = (_s = _x.call(_i)).done) && (_arr.push(_s.value), _arr.length !== i); _n = !0); } catch (err) { _d = !0, _e = err; } finally { try { if (!_n && null != _i.return && (_r = _i.return(), Object(_r) !== _r)) return; } finally { if (_d) throw _e; } } return _arr; } }\nfunction _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }\nfunction Component(_ref) {\n  var record = _ref.record,\n    ctx = _ref.ctx,\n    subtable = _ref.subtable,\n    rowInfo = _ref.rowInfo;\n  return /*#__PURE__*/_react.default.createElement(\"div\", null, Object?.entries(record)?.map(function (_ref2, index) {\n    var _ref3 = _slicedToArray(_ref2, 2),\n      key = _ref3[0],\n      value = _ref3[1];\n    return /*#__PURE__*/_react.default.createElement(\"div\", {\n      key: key,\n      style: {\n        display: \"flex\"\n      }\n    }, /*#__PURE__*/_react.default.createElement(\"div\", {\n      style: {\n        color: \"#000\",\n        fontSize: \"16px\",\n        fontWight: 600\n      }\n    }, rowInfo?.[key]?.label, \":\"), /*#__PURE__*/_react.default.createElement(\"div\", {\n      style: {\n        color: \"#000\",\n        fontSize: \"16px\"\n      }\n    }, value));\n  }));\n}"
  },
  "checkbox": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [],
    "dataTableDisabled": false,
    "isInSubForm": true,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgcqdbsbzb",
    "dataField": "wxxjddfbfxgc",
    "fieldLength": null,
    "dataBind": "checkbox_0kwog3aq1b5o5ln7x1",
    "label": "危险性较大的分部分项工程",
    "labelHidden": false,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": false,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "change",
    "showLabel": false,
    "dataSourceType": "dictionary",
    "options": [
      {
        "code": "1",
        "value": " blank-1",
        "aySerial": 1,
        "soleNum": " blank-1",
        "ovalue": " ",
        "label": " "
      }
    ],
    "dictionaryType": " blank",
    "dataSourceFn": "",
    "defaultValue": [
      " blank-true"
    ],
    "direction": "vertical",
    "multiple": true
  },
  "radio": {
    "visible": true,
    "classNames": [],
    "labelClassNames": [],
    "events": [
      {
        "event": "change",
        "codeItem": {
          "code": "module.exports = function (params, ctx, block) {\n  const wdgc = ctx.getValue(\"radio_mz2btbjy3anoknghat\");\n  debugger;\n  if (wdgc == \"Dangerous Construction Works-Large-scale High-risk Works\") {\n    ctx.message(\n      \"请上传附件《专项施工方案专家论证材料（签字盖章版）》\",\n      \"warning\",\n    );\n  }\n};\n",
          "utils": []
        }
      }
    ],
    "dataTableDisabled": false,
    "isInSubForm": false,
    "virtualField": false,
    "virtualBindingTable": "",
    "virtualBindingField": "",
    "dataTable": "tud_wdgczxsgbsb",
    "dataField": "sfcwd",
    "fieldLength": null,
    "dataBind": "radio_mz2btbjy3anoknghat",
    "label": "是否超危大",
    "labelHidden": true,
    "labelCustomWidth": false,
    "useLabelWidth": true,
    "labelWidth": "100px",
    "labelSpan": 2,
    "labelAlign": "center",
    "columnWidth": "200px",
    "columnGroup": "",
    "readonly": false,
    "required": false,
    "disabled": true,
    "allowClear": false,
    "validatorFunc": "",
    "validatorScriptRefId": "",
    "watches": [],
    "actions": [],
    "validateMode": "submit",
    "showLabel": false,
    "dataSourceType": "dictionary",
    "options": [
      {
        "code": "High-risk Divisional",
        "value": "Dangerous Construction Works-High-risk Divisional",
        "soleNum": "Dangerous Construction Works-High-risk Divisional",
        "ovalue": "危险性较大的分部分项工程",
        "label": "危险性较大的分部分项工程"
      },
      {
        "code": "Large-scale High-risk Works",
        "value": "Dangerous Construction Works-Large-scale High-risk Works",
        "soleNum": "Dangerous Construction Works-Large-scale High-risk Works",
        "ovalue": "超过一定规模的危险性较大的分部分项工程",
        "label": "超过一定规模的危险性较大的分部分项工程"
      }
    ],
    "dictionaryType": "Dangerous Construction Works",
    "dataSourceFn": "",
    "defaultValue": "Dangerous Construction Works-High-risk Divisional",
    "direction": "vertical"
  }
};
